# Generated by Django 5.2.3 on 2025-06-11 08:25

import django.db.models.deletion
import goal_star.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名稱')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('deadline', models.DateTimeField(default=goal_star.models.get_default_deadline, verbose_name='截止日期')),
                ('state', models.CharField(choices=[('in_progress', '進行中'), ('pending_verification', '等待驗證'), ('completed', '完成'), ('verification_timeout', '驗證超時')], default='in_progress', max_length=20, verbose_name='狀態')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to=settings.AUTH_USER_MODEL, verbose_name='使用者')),
            ],
            options={
                'verbose_name': '目標',
                'verbose_name_plural': '目標',
                'ordering': ['deadline'],
            },
        ),
    ]
